#+title: lsp-inspector.el
#+author: Naoya Yamashita
#+date: 2020-03-20

[[https://github.com/conao3/lsp-inspector.el][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/lsp-inspector.el.png]]
[[https://github.com/conao3/lsp-inspector.el/blob/master/LICENSE][https://img.shields.io/github/license/conao3/lsp-inspector.el.svg?style=flat-square]]
[[https://github.com/conao3/lsp-inspector.el/releases][https://img.shields.io/github/tag/conao3/lsp-inspector.el.svg?style=flat-square]]
[[https://github.com/conao3/lsp-inspector.el/actions][https://github.com/conao3/lsp-inspector.el/workflows/Main%20workflow/badge.svg]]

* Overview

lsp-inspector.el provides an inspector for Language Server Protocol (LSP) messaging within Emacs. It serves as an Emacs-native implementation inspired by Microsoft's [[https://github.com/Microsoft/language-server-protocol-inspector][Language Server Protocol Inspector]], allowing you to monitor and debug communication between lsp-mode and language servers.

* Requirements

- Emacs 26.1 or later

* Installation

** Using leaf (recommended)

#+begin_src emacs-lisp
(leaf lsp-inspector :ensure t)
#+end_src

** Using use-package

#+begin_src emacs-lisp
(use-package lsp-inspector
  :ensure t)
#+end_src

** Manual Installation

Clone this repository and add it to your load-path:

#+begin_src emacs-lisp
(add-to-list 'load-path "/path/to/lsp-inspector.el")
(require 'lsp-inspector)
#+end_src

* Usage

After installation, lsp-inspector integrates with lsp-mode to provide inspection capabilities for LSP messages exchanged between Emacs and your language servers.

* Contributing

Contributions are welcome. Please feel free to submit issues and pull requests.

** Development Setup

Install [[https://github.com/cask/cask][Cask]] for dependency management:

#+begin_src shell
# macOS
brew install cask

# Manual installation
git clone https://github.com/cask/cask ~/.cask
export PATH="$HOME/.cask/bin:$PATH"
#+end_src

** Running Tests

#+begin_src shell
make test
#+end_src

* License

This project is licensed under the GNU General Public License v3.0. See the [[https://github.com/conao3/lsp-inspector.el/blob/master/LICENSE][LICENSE]] file for details.

* Author

Naoya Yamashita ([[https://github.com/conao3][conao3]])
